### ISSUE TITLE
Choose allows empty input

### ISSUE THREAD

**Issue by spotlightishere** [Yuuki-Discord/Yuuki-Bot#74]
As the title says. This should be relatively easy to fix - cannot do it at the moment, so I'm putting it here for reference.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/10055256/103424609-ebd6a600-4b72-11eb-8dcd-cff9cc653e3b.png">

**Comment by Erisa** [comment]
While looking into this I found a mildly funny thing:
```rb
    # The choose command does not require extra_commands to be enabled.
    YuukiBot.crb.add_command(
      :choose,
      code: proc { |event, args|
        event.respond("I choose #{args.sample}!")
      }
    )
```
Contrary to this comment, the `choose` command does in fact require `extra_commands` to be enabled.

I do not however have any idea why this is the case, since it's outside of the `if YuukiBot.config['extra_commands']` block.
Regardless though it's current location inside `json_cmds.rb` seems like a bad place to put it.

So I moved it. Arguably it's new place inside `utility/say.rb` is also not a very great place but short of creating more files it was the first that came to mind.
